packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': false
  '@swc/core': false
  bcrypt: false
  core-js: false
  sharp: false
  unrs-resolver: false

pmOnFail: ignore
